// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4PHMM_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ZIPHMM_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ZIPHMM2_INF_1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ZIPHMM_INF_1_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4PHMM_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PHMM_mod, 0},
    {"_rcpp_module_boot_stan_fit4ZIPHMM_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ZIPHMM_mod, 0},
    {"_rcpp_module_boot_stan_fit4ZIPHMM2_INF_1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ZIPHMM2_INF_1_mod, 0},
    {"_rcpp_module_boot_stan_fit4ZIPHMM_INF_1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ZIPHMM_INF_1_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Bayeshmmcts(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
